server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/celula
    username: postgres
    password: eHmTzE45Of
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/master/db.changelog-master.xml
    enabled: on