--liquibase formatted sql

--changeset seu-nome:01
CREATE TABLE igreja (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP
);
