--liquibase formatted sql

--changeset seu-nome:02
CREATE TABLE pessoa (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        telefone VARCHAR(255),
                        rua VARCHAR(255),
                        numero VARCHAR(50),
                        complemento VARCHAR(255),
                        bairro VARCHAR(255),
                        cidade VARCHAR(255),
                        estado VARCHAR(2),
                        cep VARCHAR(10),
                        has_celula BOOLEAN NOT NULL,
                        atribuicao VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP,
                        CONSTRAINT chk_atribuicao CHECK (atribuicao IN ('LIDER', 'LIDER_TREINAMENTO', 'ANFRITRIAO', 'MEMBRO'))
);
