--liquibase formatted sql

--changeset seu-nome:02
CREATE TABLE pessoa (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        telefone VARCHAR(255),
                        has_celula BOOLEAN NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP
);
