--liquibase formatted sql

--changeset seu-nome:03
CREATE TABLE celula (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        igreja_id BIGINT,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP,
                        CONSTRAINT fk_igreja FOREIGN KEY (igreja_id) REFERENCES igreja(id)
);
