--liquibase formatted sql

--changeset seu-nome:03
CREATE TABLE celula (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        igreja_id BIGINT,
                        rua VARCHAR(255),
                        numero VARCHAR(50),
                        complemento VARCHAR(255),
                        bairro VARCHAR(255),
                        cidade VARCHAR(255),
                        estado VARCHAR(2),
                        cep VARCHAR(10),
                        dia_semana VARCHAR(10) NOT NULL,
                        horario TIME NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP,
                        CONSTRAINT fk_igreja FOREIGN KEY (igreja_id) REFERENCES igreja(id),
                        CONSTRAINT chk_dia_semana CHECK (dia_semana IN ('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO'))
);
