--liquibase formatted sql
--changeset seu-nome:06
CREATE TABLE contribuicao (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              celula_id BIGINT NOT NULL,
                              data_celula TIMESTAMP NOT NULL,
                              valor_arrecadado DECIMAL(19,2) NOT NULL,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP,
                              CONSTRAINT fk_contribuicao_celula FOREIGN KEY (celula_id) REFERENCES celula(id)
);

--liquibase formatted sql
CREATE TABLE contribuinte (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pessoa_id BIGINT NOT NULL,
                              contribuicao_id BIGINT NOT NULL,
                              valor_contribuido DECIMAL(19,2) NOT NULL,
                              has_contribuiu BOOLEAN NOT NULL,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP,
                              CONSTRAINT fk_contribuinte_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa(id),
                              CONSTRAINT fk_contribuinte_contribuicao FOREIGN KEY (contribuicao_id) REFERENCES contribuicao(id)
);
